### ISSUE TITLE
Feature: publish Spring Boot configuration metadata

### ISSUE THREAD

**Issue by lbruun** [lbruun-net/Pre-Liquibase#26]
To aid IDEs it would be nice if the project published configuration metadata.

https://docs.spring.io/spring-boot/docs/current/reference/html/configuration-metadata.html

Priority:  nice-to-have

**Comment by zorglube** [comment]
Integrated into : https://github.com/lbruun/Pre-Liquibase/pull/29

**Comment by lbruun** [comment]
Implemented in version `1.5.1`.
