### ISSUE TITLE
Incompatible with Spring Boot 3.4.0

### ISSUE THREAD

**Issue by candrews** [lbruun-net/Pre-Liquibase#35]
Spring Boot 3.4.0 was released yesterday: https://spring.io/blog/2024/11/21/spring-boot-3-4-0-available-now

Projects using Pre-Liquibase and Spring Boot 3.4.0 fail to start with this error:
```
An attempt was made to call a method that does not exist. The attempt was made from the following location:

    net.lbruun.springboot.preliquibase.PreLiquibaseAutoConfiguration$DefaultPreLiquibaseDataSourceProvider.<init>(PreLiquibaseAutoConfiguration.java:216)

The following method did not exist:

    'liquibase.integration.spring.SpringLiquibase org.springframework.boot.autoconfigure.liquibase.LiquibaseAutoConfiguration$LiquibaseConfiguration.liquibase(org.springframework.beans.factory.ObjectProvider, org.springframework.beans.factory.ObjectProvider, org.springframework.boot.autoconfigure.liquibase.LiquibaseProperties, org.springframework.boot.autoconfigure.liquibase.LiquibaseConnectionDetails)'

The calling method's class, net.lbruun.springboot.preliquibase.PreLiquibaseAutoConfiguration$DefaultPreLiquibaseDataSourceProvider, was loaded from the following location:

    jar:file:/home/candrews/.gradle/caches/modules-2/files-2.1/net.lbruun.springboot/preliquibase-spring-boot-autoconfigure/1.5.1/87c14b1dc682b7802c903fb20200f7419e189d73/preliquibase-spring-boot-autoconfigure-1.5.1.jar!/net/lbruun/springboot/preliquibase/PreLiquibaseAutoConfiguration$DefaultPreLiquibaseDataSourceProvider.class

The called method's class, org.springframework.boot.autoconfigure.liquibase.LiquibaseAutoConfiguration$LiquibaseConfiguration, is available from the following locations:

    jar:file:/home/candrews/.gradle/caches/modules-2/files-2.1/org.springframework.boot/spring-boot-autoconfigure/3.4.0/2cf78b01be25952c96cb8ee60b4b0562b3a136f2/spring-boot-autoconfigure-3.4.0.jar!/org/springframework/boot/autoconfigure/liquibase/LiquibaseAutoConfiguration$LiquibaseConfiguration.class

The called method's class hierarchy was loaded from the following locations:

    org.springframework.boot.autoconfigure.liquibase.LiquibaseAutoConfiguration.LiquibaseConfiguration: file:/home/candrews/.gradle/caches/modules-2/files-2.1/org.springframework.boot/spring-boot-autoconfigure/3.4.0/2cf78b01be25952c96cb8ee60b4b0562b3a136f2/spring-boot-autoconfigure-3.4.0.jar


Action:

Correct the classpath of your application so that it contains compatible versions of the classes net.lbruun.springboot.preliquibase.PreLiquibaseAutoConfiguration$DefaultPreLiquibaseDataSourceProvider and org.springframework.boot.autoconfigure.liquibase.LiquibaseAutoConfiguration$LiquibaseConfiguration
```

The signature of [`LiquibaseAutoConfiguration.LiquibaseConfiguration.liquibase`](https://github.com/spring-projects/spring-boot/blob/v3.4.0/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/liquibase/LiquibaseAutoConfiguration.java#L102) has changed - the commit that made the change is https://github.com/spring-projects/spring-boot/commit/6aeab4461e7fb821c3954efe5efdaec0885cd3f6#diff-3690614f74b4c856a949f9746fd77a870c9d32fc90ade726e515780a17c65a2aL101

**Comment by alessiomatricardi** [comment]
+1, seems that `org.springframework.boot.autoconfigure.liquibase.LiquibaseAutoConfiguration.LiquibaseConfiguration#liquibase` has changed and has package access

**Comment by lbruun** [comment]
Thank you for reporting. Appreciated. 
I'm on it.

**Comment by lbruun** [comment]
Until this is fixed in Pre-Liquibase you can solve it by wiring a bean of type [PreLiquibaseDataSourceProvider](https://javadoc.io/doc/net.lbruun.springboot/preliquibase-spring-boot-autoconfigure/latest/net/lbruun/springboot/preliquibase/PreLiquibaseDataSourceProvider.html) in your application.
This means that you take explicit control over the selection of the `DataSource` which Pre-Liquibase uses for its execution. In an application with only one `DataSource`, this would be trivial to implement in the application's config.

By doing this the Pre-Liquisebase auto-configuration code will not execute into the code path where it currently fails.

**Comment by lbruun** [comment]
Version `1.6.0`  has been published to Maven Central. This version is compatible with Spring Boot 3.4.

(from experience it takes 5-30 minutes before it is available for consumption and some hours before it is available in Central's index)
